name: publish Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  publish-hello-docker-image::
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the test-docker Docker image
      uses: docker/login-action@v1
      with:
      registry: ghcr.io
      username: ${{ github.actor }}
      password: ${{ secrets.PAT_TOKEN }}
      run: |
           docker build . --tag ghcr.io/puneethgcr/test-docker-gcr-demo:latest
           docker run ghcr.io/puneethgcr/test-docker-gcr-demo:latest
           docker push ghcr.io/puneethgcr/test-docker-gcr-demo:latest
